### ISSUE TITLE
Problems with elastic stack 8.5

### ISSUE THREAD

**Issue by cealpa** [Zimbra/elastic-stack#3]
Hi, 
 
I'm trying to deploy on elastic 8.5, but can't get it to work correctly.

When creating the "data view", I get the following message:

"A field is defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data."

Is this project compatible with Elastic stack 8.5?

sorry for my poor english. Thanks.

Regards.

**Comment by ghost** [comment]
Not yet, I am having issues installing ELK 8 myself, you can use version 7 till then

**Comment by ghost** [comment]
the guide has been updated for ELK 8.x

**Comment by cealpa** [comment]
Thank you very much for your answer and your great work.
